### ISSUE TITLE
safari shows a border in paper-textarea?

### ISSUE THREAD

**Issue by gertcuykens** [PolymerElements/paper-input#176]
example http://gcl-12.appspot.com

![image](https://cloud.githubusercontent.com/assets/863731/9778020/3bcd71f4-576b-11e5-933e-c5fb7e3c3057.png)

**Comment by notwaldorf** [comment]
What version of `paper-input`/`iron-autogrow-textarea` are you using? I don't see this in the elements catalog in safari: :(

<img width="704" alt="screen shot 2015-09-09 at 8 32 08 pm" src="https://cloud.githubusercontent.com/assets/1369170/9779579/dd6bfccc-5731-11e5-8ce5-730503f6ab79.png">

**Comment by notwaldorf** [comment]
I did some more investigating, and removing the `brm-form` style from the `paper-input` removes the border -- maybe it's something you're applying specifically?

**Comment by gertcuykens** [comment]
hmm but I don't see it in chrome? ok i will try a few things first

**Comment by gertcuykens** [comment]
This is the style inside the brm-form template but when I remove it, I still have the same border.
```css
        <style>
            paper-toolbar {
                background: transparent;
                box-sizing: border-box;
                color: black;
            }
    
            paper-checkbox::shadow #ink {color: #4285f4;}
            paper-checkbox::shadow #checkbox.checked {background-color: #4285f4; border-color: #4285f4;}
            
            paper-radio-button::shadow #ink[checked] {color: #4285f4;}
            paper-radio-button::shadow #onRadio {background-color: #4285f4; border-color: #4285f4;}
            paper-radio-button[checked]::shadow #offRadio {border-color: #4285f4;}
            paper-radio-button {padding: 0px !important;}
            
            paper-fab {color: #fff; background: #5677fc;}
            paper-tooltip {z-index: 999; margin-top:-15px;}   
    
            table, td {border-collapse: collapse; padding:0; margin:0;}
            
            td {height:48px;}
            
            .upper {
                text-transform: uppercase;
                --paper-input-container-input: {text-transform: uppercase;};
            }
            
            .required {--paper-checkbox-unchecked-color: #D34336;}
        </style>
```

Note that in safari as soon as I fill something in, the border disappears.
