### ISSUE TITLE
--iron-icon-width no longer works

### ISSUE THREAD

**Issue by summers173** [PolymerElements/paper-input#207]
In this link you have and example in the "Prefixes and Suffixes" section

https://elements.polymer-project.org/bower_components/paper-input/demo/index.html

with this code 

    paper-icon-button {
      color: var(--paper-red-300);
      --paper-icon-button-ink-color: var(--paper-red-a100);
      --iron-icon-width: 15px;
      --iron-icon-height: 15px;
      padding: 0px 4px;
    }

you make the prefix and suffix smaller, but now this no longer works.

I believe in the v1.1.4 this was broken (I made myself a fix adding height: 24px; with the --paper-icon-button mixin), but now in v1.1.5 all the icons looks smaller.

I delete my fix and everything works EXCEPT  the mixins:

--iron-icon-width: 15px;
--iron-icon-height: 15px;

I made myself a work around until this is fixed again.

Regards

**Comment by notwaldorf** [comment]
Ah, you're right. All you have to do is change the width and height of the `paper-icon-button` itself:
```css
paper-icon-button {
  color: var(--paper-red-300);
  --paper-icon-button-ink-color: var(--paper-red-a100);
  width: 15px;
  height: 15px;
  padding: 0px 4px;
}
```

I will add a fix for this. Thanks!
