### ISSUE TITLE
Disable spinner on `type='number'`

### ISSUE THREAD

**Issue by David-Mulder** [PolymerElements/paper-input#279]
So, you can do this using CSS using

```
input[type="number"]::-webkit-outer-spin-button,
input[type="number"]::-webkit-inner-spin-button {
  -webkit-appearance: none;
  margin: 0;
}
input[type="number"] {
  -moz-appearance: textfield;
}
```

so this can only be achieved right now on Firefox with the current set up. There are two ways this could be exposed:
1. Add a Chrome (`::-webkit-inner-spin-button`) /Safari (`::-webkit-outer-spin-button`) specific mixin, thus the user will have to write something like
   
   ```
   paper-input {
     --paper-input-container-input-webkit-spinner: {
       -webkit-appearance: none;
       margin: 0;
     }
     -moz-appearance: textfield;
   }
   ```
2. Add a `no-number-spinner` attribute which applies the CSS for the user instead.

**Comment by notwaldorf** [comment]
I think adding the mixins should work. Are there no `ms-` or `moz` versions also?

**Comment by David-Mulder** [comment]
@notwaldorf Well, I already included the `-moz` example in my OP, that's why I was a bit hesitant about the mixin ;-) And regarding Edge: No spinner to be seen there as of yet (though I guess a new mixin would need to be added once they do add a spinner as you can't have the same mixin due to hacks like the `margin` thingy).

**Comment by notwaldorf** [comment]
@David-Mulder would you mind sending a PR to add these mixins?

**Comment by flyweight** [comment]
The `--paper-input-container-input-webkit-spinner` mixin is no longer working for me in paper-input-container using `v1.1.22`

### This does not remove the spinner:

**paper-input/paper-input-container.html**
```
      .input-content ::content input::-webkit-outer-spin-button,                                                                            
      .input-content ::content input::-webkit-inner-spin-button {                                                                           
        @apply(--paper-input-container-input-webkit-spinner);                                                                               
        display: none;                                                                                                                      
        margin: 0;                                                                                                                          
        -webkit-appearance: none;                                                                                                           
      }  
```

### This removes the spinner:

**paper-input/paper-input.html**
```
<dom-module id="paper-input">                                                                                                               
  <template>                                                                                                                                
    <style>                                                                                                                                 
      :host {                                                                                                                               
        display: block;                                                                                                                     
      }                                                                                                                                     
                                                                                                                                            
      :host([focused]) {                                                                                                                    
        outline: none;                                                                                                                      
      }                                                                                                                                     
                                                                                                                                            
      :host([hidden]) {                                                                                                                     
        display: none !important;                                                                                                           
      }                                                                                                                                     
                                                                                                                                            
      input::-webkit-outer-spin-button,                                                                                                     
      input::-webkit-inner-spin-button {                                                                                                    
        @apply(--paper-input-container-input-webkit-spinner);                                                                               
        display: none;                                                                                                                      
        margin: 0;                                                                                                                          
        -webkit-appearance: none;                                                                                                           
      }
```

Am I doing something wrong?  Are the selectors in `paper-input-container` no longer valid?

**Comment by wq9** [comment]
The `--paper-input-container-input-webkit-spinner` mixin is not working for `paper-input-container` v1.1.23.

I'm putting this in `paper-input/paper-input.html`:
```css
:host([hidden]) {
        display: none !important;
      }

      input::-webkit-outer-spin-button,                                                                                                     
      input::-webkit-inner-spin-button {                                                                                                    
        @apply(--paper-input-container-input-webkit-spinner);                                                                                                                                                                                      
      }
      input::-webkit-clear-button {
        @apply(--paper-input-container-input-webkit-clear);  
      }
```
