### ISSUE TITLE
[ paper-textarea ] .mirror-text beyond the limit ( firefox 42.0 )

### ISSUE THREAD

**Issue by ibmsdave** [PolymerElements/paper-input#286]
Hi! 
in firefox 42.0
https://elements.polymer-project.org/elements/paper-input?view=demo:demo/index.html&active=paper-textarea
![screenshot-elements polymer-project org 2015-12-16 12-14-49](https://cloud.githubusercontent.com/assets/6049644/11836911/b91144a4-a3ee-11e5-847e-3fdcacd350a7.png)

.mirror-text beyond the limit

I solved this problem by adding the parent of the style:

```css
paper-input-decorator .mirror-text {
    white-space: normal;
    word-break: break-all;
}
```

it's a bug or a feature? )
