### ISSUE TITLE
paper-textarea disapear in a container with display:flex

### ISSUE THREAD

**Issue by maxiplay** [PolymerElements/paper-input#299]

**Comment by notwaldorf** [comment]
Interesting, that's totally a bug. Taking a look.

**Comment by notwaldorf** [comment]
In the meantime, a workaround is to add something like 
```css
paper-textarea {
  min-width: 170px;
}
```
