### ISSUE TITLE
Make paper-input-error inside paper-input position: static;

### ISSUE THREAD

**Issue by swypse** [PolymerElements/paper-input#500]
I have:

```css
paper-input {
    --paper-input-error: {
        /* ... */
        position: static !important;
    };
}
```

But in paper-input-error is:

```css
:host {
    /* ... */
    @apply --paper-input-error;
    position: absolute; /* this line breaks the position: static !important; from parent. */
}
```

Can i change this behavior?
