### ISSUE TITLE
-paper-input-container-underline-focus not coloring underline 

### ISSUE THREAD

**Issue by dman777** [PolymerElements/paper-input#528]
### Description
`--paper-input-container-underline-focus` mixin does not take effect when coloring the underline that is in focus

using paper-input "version": "1.1.23",

### Expected outcome

When clicking on paper input element and entering text, the underline color changes

### Actual outcome

underline stays default color blue when clicked on and typing
### Steps to reproduce
```css
        
      paper-input, paper-textarea {
        --paper-input-container-label-focus: {
          color: var(--focus-label);
        }
        
        --paper-input-container-underline-focus: {
          background-color: red;
          background: red;
          color: red;
        }
}
```
```html
        <div class="horizontal layout wrap justified">
          <paper-input
            style="min-width: 400px"
            name="title"
            label="Posting title *" 
            char-counter="37"
            maxlength="37"
            error-message="* Required"
            required></paper-input>
        </div>
```

### Browsers Affected

- [x ] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10
