### ISSUE TITLE
how to custom input style when component is disabled?

### ISSUE THREAD

**Issue by robertop87** [PolymerElements/paper-input#539]
I saw in the older documentation the mixin **--paper-input-container-input-disabled,** I want to use something similar in order to custom input text background color.

is it possible with the current mixins? (after a while I could not get this working)

**Comment by robertop87** [comment]
PR: https://github.com/PolymerElements/paper-input/pull/540

**Comment by frami** [comment]
I have the same issue. I need to change the background color when the paper-input is disabled. Would be great if the PR #540 will be soon integrated.

**Comment by bennypowers** [comment]
Here are some workarounds, although I agree that properties should be exposed for `.floating-label-placeholder` and `:host[disabled] .floating-label-placeholder`

```css
      #searchInput {
        --primary-color: white;
        --primary-text-color: white;
        --paper-input-container-label-floating: white;
        --paper-input-container-label: {
          color: var(--paper-grey-100);
        };
        --paper-font-caption: {
          color: white;
        };
      }

      #searchInput[disabled] {
        --paper-font-caption: {
          color: var(--paper-grey-100);
        };
      }
```
