### ISSUE TITLE
font bug

### ISSUE THREAD

**Issue by gertcuykens** [PolymerElements/paper-input#92]
https://github.com/Polymer/paper-input/issues/128

```css
body{
       font-family: 'RobotoDraft', sans-serif;
       line-height: 140%;
 }
```
bug: (messes up line height on each line added)
```html
<iron-autogrow-textarea id="a1">
         <textarea id="t1" name="intro"></textarea>
</iron-autogrow-textarea>
```
fix:
```html
<iron-autogrow-textarea id="a1">
        <textarea id="t1" name="intro" style="font:inherit;"></textarea>
</iron-autogrow-textarea>
```
